version: '3.8' 
volumes: 
  peter-zk001-volume: 
    name: peter-zk001-volume 
  peter-zk002-volume: 
    name: peter-zk002-volume 
  peter-zk003-volume: 
    name: peter-zk003-volume 
    
services: 
  peter-zk001: 
    image: test-zookeeper 
    container_name: peter-zk001
    restart: always 
    hostname: peter-zk001
    environment: 
      MY_ID: 1
    volumes: 
      - peter-zk001-volume:/data
      
  peter-zk002: 
    image: test-zookeeper 
    container_name: peter-zk002
    restart: always 
    hostname: peter-zk002
    environment: 
      MY_ID: 2
    volumes: 
      - peter-zk002-volume:/data
  
  peter-zk003: 
    image: test-zookeeper 
    container_name: peter-zk003
    restart: always 
    hostname: peter-zk003
    environment: 
      MY_ID: 3
    volumes: 
      - peter-zk003-volume:/data
    
networks: 
  default: 
    external: 
      name: zoo
