version: '3'

services:
    zookeeper-local:
        image: wurstmeister/zookeeper
        container_name: zookeeper-local
        ports:
            - "2181:2181"

    kafka-local-001:
        image: wurstmeister/kafka
        hostname: kafka-local-001
        container_name: kafka-local-001
        restart: on-failure
        ports:
        - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_HOST_NAME: kafka-local-001
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181/peter-kafka
            KAFKA_LISTENERS: INTERNAL://kafka-local-001:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-local-001:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        depends_on:
        - zookeeper-local

    kafka-local-002:
        image: wurstmeister/kafka
        hostname: kafka-local-002
        container_name: kafka-local-002
        restart: on-failure
        ports:
        - "9093:9093"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ADVERTISED_PORT: 9093
            KAFKA_ADVERTISED_HOST_NAME: kafka-local-002
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181/peter-kafka
            KAFKA_LISTENERS: INTERNAL://kafka-local-002:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-local-002:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        depends_on:
        - zookeeper-local

    kafka-local-003:
        image: wurstmeister/kafka
        hostname: kafka-local-003
        container_name: kafka-local-003
        restart: on-failure
        ports:
        - "9094:9094"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ADVERTISED_PORT: 9094
            KAFKA_ADVERTISED_HOST_NAME: kafka-local-003
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181/peter-kafka
            KAFKA_LISTENERS: INTERNAL://kafka-local-003:9094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-local-003:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        depends_on:
        - zookeeper-local