FROM ubuntu:18.04
RUN mkdir -p /root/install
RUN apt-get update

WORKDIR /root/install

# java 설치 준비 
ENV DEBIAN_FRONTEND noninteractive
ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-arm64

# java 및 유틸 설치 
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install wget -y 
RUN apt-get install vim -y 
RUN apt-get install net-tools

# kafka 설치 
RUN wget https://archive.apache.org/dist/kafka/2.7.0/kafka_2.13-2.7.0.tgz
RUN tar -zxvf kafka_2.13-2.7.0.tgz 
RUN mv kafka_2.13-2.7.0 /usr/local/kafka

# 설정파일 및 초기화 파일 복사 
COPY config/init.sh init.sh
COPY config/server.properties /usr/local/kafka/config/server.properties

CMD bash init.sh
